services:
  db:
    image: postgres:15-alpine
    container_name: fantasy_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fantasy_db
    ports:
      - "5433:5432" # Host Port 5433 (Safe from conflicts)
    volumes:
      - fantasy_data:/var/lib/postgresql/data

volumes:
  fantasy_data: